// Generated by scripts/generate-provider-host-contracts.ts.
// This release-only shim is derived from host imports; do not edit by hand.

export type DeleteObjectRequest<T = any, U = any, V = any, W = any, X = any> = any;
export const DeleteObjectRequest: any = undefined;
export type getActiveSyncGatewayAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const getActiveSyncGatewayAdapter: any = undefined;
export type PresignDownloadRequest<T = any, U = any, V = any, W = any, X = any> = any;
export const PresignDownloadRequest: any = undefined;
export type PresignDownloadResponse<T = any, U = any, V = any, W = any, X = any> = any;
export const PresignDownloadResponse: any = undefined;
export type PresignUploadRequest<T = any, U = any, V = any, W = any, X = any> = any;
export const PresignUploadRequest: any = undefined;
export type PresignUploadResponse<T = any, U = any, V = any, W = any, X = any> = any;
export const PresignUploadResponse: any = undefined;
export type ProviderAdminAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const ProviderAdminAdapter: any = undefined;
export type registerProviderAdminAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const registerProviderAdminAdapter: any = undefined;
export type registerStorageGatewayAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const registerStorageGatewayAdapter: any = undefined;
export type StorageGatewayAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const StorageGatewayAdapter: any = undefined;
export type SyncGatewayAdapter<T = any, U = any, V = any, W = any, X = any> = any;
export const SyncGatewayAdapter: any = undefined;
